services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=Cursos_Arte_Da_Guerra
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./Arte_Da_Guerra
    container_name: backend
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_OFICIAL=Cursos_Arte_Da_Guerra
      - DB_TEST=test
      - JWT_SECRET=CURSOSDEARTESMARCIAISARTEDAGUERRACODIFICACOES
      - FRONT_URL=/api/
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./my-app
    container_name: frontend
    environment:
      - VITE_API_URL=/api/
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
