version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./Arte_Da_Guerra
    container_name: backend
    env_file:
      - ./Arte_Da_Guerra/.env
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./my-app
    container_name: frontend
    env_file:
      - ./my-app/.env
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/cursoartedaguerracert.pem:/etc/nginx/certs/cursoartedaguerracert.pem:ro
      - ./certs/cursoartedaguerrakey.pem:/etc/nginx/certs/cursoartedaguerrakey.pem:ro
    env_file:
      - ./.env
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
